name: first

on: [push]

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v4
      - name: Step Two
        run: env | sort

  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step One
        uses: actions/checkout@v4
      - name: Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"
      - name: AWS Sustainability Scanner GitHub Action
        uses: aws-actions/sustainability-scanner@v1
        with:
          # File path of the CloudFormation template to be scanned
          file: # optional
          # Directory path with CloudFormation files to be scanned
          directory: # optional, default is .
          # CDK stack name to be scanned
          stack_name: # optional
          # File path to extend set of rules
          rules_file: # optional
                

